server:
  port: 9000

spring:
  application:
    name: Market-User

eureka:
  instance:
    hostname: localhost
    instance-id: Market-User   #服务名#
    prefer-ip-address: true  # 访问路径可以显示ip
  client:
    service-url:
      defaultZone: http://server1.com:7001/eureka/

# 配置点击某个服务后跳转到相应的监控信息info页面，http://192.168.190.1:8080/actuator/info
info:
  app.name: MarketUser
  build.artifactId: $project.artifactId$
  build.version: $project.version$


feign:
  hystrix:
    enabled: true
